name: Docs

on:
  workflow_dispatch:

jobs:
  Docs:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout doxygen awesome
      uses: actions/checkout@v3
      with:
        repository: jothepro/doxygen-awesome-css
        path: doxygen-awesome-css
    - name: Install doxygen
      run: sudo apt-get update && sudo apt-get install doxygen graphviz -y
    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile
    - name: Copy LICENSE
      run: cp doxygen-awesome-css/LICENSE docs/html/LICENSE
    - name: Create .nojekyll
      run: touch docs/html/.nojekyll
    - name: Deploy Documentation to branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: docs
        folder: docs/html