name: Release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Release Tag'
        type: string
      changelog:
        description: 'Changelog'
        type: string
      draft:
        description: 'Draft'
        type: boolean
      prerelease:
        description: 'Pre-release'
        type: boolean

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Copy LICENSE
      run: cp LICENSE include/LICENSE
    - name: Install zip
      run: |
        sudo apt update
        sudo apt install -y zip
    - name: Zip headers
      run: zip -r KTL.zip include
    - name: Tar headers
      run: tar czvf KTL.tar.gz include
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          KTL.zip
          KTL.tar.gz
        tag_name: ${{ inputs.tagName }}
        body: ${{ inputs.changelog }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        fail_on_unmatched_files: true